### PR TITLE
Rewrite sample bar client

### PR DESCRIPTION
**Pull request by marie-bnl**

### CODE REVIEW

**Comment by kris7t** [comment]
Thanks, this is looking great!

Btw, I think `docs/DBUS.md` should also be changed to point out the new client.

**Comment by marie-bnl** [comment]
Actually the whole section regarding the bar implementation will need to be rewritten, first because commands changed, and also to mention the flags

**Comment by kris7t** [comment]
I guess another option would be to just point users to the `--help` flag. Bit more future proof (if the script is changed, the documentation doesn't necessarily has to be changed), although a bit less friendly for readers.

**Comment by marie-bnl** [comment]
It seems like a best idea, and I'm not even sure about the less-friendliness as I think those help menus are pretty clear and users that would use such features are typically used to reading help menus and man pages

**Comment by marie-bnl** [comment]
So I updated the documentation, removing occurences of waybar to replace it with the more generalist "status bar" expression, fixing the file name and referring to --help menus

**Pull request merged**
